# Generated by Django 5.0.6 on 2024-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_tool", models.CharField(max_length=15)),
                ("type", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=50)),
                ("logo", models.ImageField(upload_to="")),
                ("affiliate_link", models.BooleanField()),
                ("webiste_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ToolRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ai_tool", models.CharField(max_length=15)),
                ("star_rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
