# Generated by Django 5.0.6 on 2024-07-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aitool",
            old_name="webiste_url",
            new_name="website_url",
        ),
    ]
