# Generated by Django 5.0.6 on 2024-07-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_rename_webiste_url_aitool_website_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="logo",
            field=models.ImageField(upload_to="logo"),
        ),
    ]
