# Generated by Django 5.0.6 on 2024-07-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_alter_aitool_logo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserDetails",
            new_name="UserDetail",
        ),
        migrations.AlterField(
            model_name="aitool",
            name="logo",
            field=models.CharField(),
        ),
    ]
