# Generated by Django 5.0.6 on 2024-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_rename_userdetails_userdetail_alter_aitool_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="affiliate_link",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="logo",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
