# Generated by Django 5.0.6 on 2024-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0005_alter_aitool_affiliate_link_alter_aitool_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="ai_tool",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="type",
            field=models.CharField(max_length=25),
        ),
    ]
