# Generated by Django 5.0.6 on 2024-07-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0006_alter_aitool_ai_tool_alter_aitool_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="description",
            field=models.CharField(),
        ),
    ]
