# Generated by Django 5.0.6 on 2024-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0007_alter_aitool_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="affiliate_link",
            field=models.BooleanField(default=False),
        ),
    ]
