# Generated by Django 5.0.6 on 2024-07-11 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0008_alter_aitool_affiliate_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="about",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="pricing_plans",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(),
                default=list,
                help_text='Enter pricing plans as JSON objects. Example: [{"name": "Basic", "price": "$10/month", "features": "Basic features"}, ...]',
                null=True,
                size=None,
            ),
        ),
    ]
