# Generated by Django 5.0.6 on 2024-07-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0009_aitool_about_aitool_pricing_plans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aitool",
            name="about",
        ),
        migrations.RemoveField(
            model_name="aitool",
            name="pricing_plans",
        ),
    ]
