# Generated by Django 5.0.6 on 2024-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0010_remove_aitool_about_remove_aitool_pricing_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
