# Generated by Django 5.0.6 on 2024-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0013_delete_userdetail_remove_toolrating_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolrating",
            name="review",
            field=models.CharField(default=None, max_length=350, null=True),
        ),
    ]
