# Generated by Django 5.0.6 on 2024-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0014_toolrating_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolrating",
            name="review",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="toolrating",
            name="star_rating",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
