# Generated by Django 5.0.6 on 2024-07-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0015_alter_toolrating_review_alter_toolrating_star_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=25)),
                ("photo_url", models.CharField(max_length=25)),
                ("testimonial", models.CharField(max_length=150)),
            ],
        ),
    ]
