# Generated by Django 5.0.6 on 2024-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0016_testimonial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aitool",
            old_name="type",
            new_name="category",
        ),
        migrations.AddField(
            model_name="aitool",
            name="about",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="features",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="aitool",
            name="media_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="logo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
