# Generated by Django 5.0.6 on 2024-07-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0017_rename_type_aitool_category_aitool_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="about",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aitool",
            name="ai_tool",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="description",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aitool",
            name="features",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aitool",
            name="media_link",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aitool",
            name="website_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
