# Generated by Django 5.0.6 on 2024-07-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0018_alter_aitool_about_alter_aitool_ai_tool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="features",
            field=models.JSONField(max_length=250),
        ),
    ]
