# Generated by Django 5.0.6 on 2024-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0020_alter_aitool_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="about",
            field=models.CharField(max_length=300),
        ),
    ]
