# Generated by Django 5.0.6 on 2024-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0021_alter_aitool_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="aitool",
            name="category",
        ),
        migrations.AlterField(
            model_name="aitool",
            name="about",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="features",
            field=models.JSONField(),
        ),
    ]
