# Generated by Django 5.0.6 on 2024-08-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0022_category_remove_aitool_category_alter_aitool_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="features",
            field=models.JSONField(default=dict),
        ),
    ]
