# Generated by Django 5.0.6 on 2024-08-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0023_alter_aitool_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="category",
            field=models.ManyToManyField(blank=True, to="tools.category"),
        ),
    ]
