# Generated by Django 5.0.6 on 2024-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0024_aitool_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="toolcategory", to="tools.category"
            ),
        ),
    ]
