# Generated by Django 5.0.6 on 2024-08-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0026_alter_aitool_about_alter_aitool_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitool",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aitool",
            name="description",
            field=models.TextField(),
        ),
    ]
