# Generated by Django 5.1 on 2024-09-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0027_alter_aitool_about_alter_aitool_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="category_display",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
