# Generated by Django 5.1 on 2025-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0028_aitool_category_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
